### ISSUE TITLE
Adding steal and steal-qunit tries to load less files but fails

### ISSUE THREAD

**Issue by imaustink** [bit-docs/bit-docs-tag-demo#7]
https://github.com/bit-docs/bit-docs-tag-demo/tree/sanity-check @matthewp clone this and try running:
```
npm install
npm test
http-server -c-1
```
Open http://localhost:8080/test/resizes/resizes-test.html

![image](https://cloud.githubusercontent.com/assets/6282922/25146221/ff2c27d2-2427-11e7-8010-7eb04ed9e1b1.png)

The file that is erroring: http://localhost:8080/test/resizes/generated-resizes-test/index.html

Can you see anything we are doing wrong?

**Comment by leoj3n** [comment]
@matthewp Please remove this line:

https://github.com/bit-docs/bit-docs-tag-demo/commit/d0b4d987e54fb4b4804a2cabd9fd9767e348105b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36

Before trying replicating these steps. Thank you!

**Comment by leoj3n** [comment]
@matthewp If you remove steal from `package.json` and `rm -rf node_modules` then `npm install`:

```
npm remove steal --save-dev
rm -rf node_modules
```

Then do the:

```
npm install
npm test
http-server -c-1
```

That file that was erroring is no longer is broken trying to load `less`:

http://localhost:8080/test/resizes/generated-resizes-test/index.html

But the QUnit test suite page:

http://localhost:8080/test/resizes/resizes-test.html

Will fail with this error:

![image](https://cloud.githubusercontent.com/assets/990216/25146977/7db4d62c-243b-11e7-9f16-bd41c37fa0d2.png)

**Comment by matthewp** [comment]
You need to add steal-less to your plugins config:

```json
{
  "steal": {
    "plugins": ["steal-less"]
  }
}
```

**Comment by justinbmeyer** [comment]
and install `steal-less` as a dev dependency

**Comment by leoj3n** [comment]
Hm, that was my intuition, and we tried that! I'm seeing the same error that we were seeing while pairing on Austin's system, which is this:

![image](https://cloud.githubusercontent.com/assets/990216/25150267/facf6bee-2446-11e7-9ce9-5072ba1bd0a7.png)

I'm guessing that we need some other bit of configuration for `steal` to find the less file.

**Comment by justinbmeyer** [comment]
@leoj3n you shouldn't.  If you have it configured correctly, it wont look for `less.js`.

**Comment by justinbmeyer** [comment]
Go through steal's progressive loading guide, you'll see it working:  http://stealjs.com/docs/StealJS.guides.progressive_loading.html

**Comment by leoj3n** [comment]
So, I added `steal-tools` (`npm i steal-tools --save-dev`) and that seems to have fixed it. Thanks for the tip @justinbmeyer
